// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using System;
using System.Collections.Generic;
using System.Text;
using Dft.lms.Localization;
using Volo.Abp.Application.Services;

namespace Dft.lms
{
    /* Inherit your application services from this class.
     */
    public abstract class lmsAppService : ApplicationService
    {
        protected lmsAppService()
        {
            LocalizationResource = typeof(lmsResource);
        }
    }
}
