// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using AutoMapper;
using Dft.lms.QuanLyDoanhNghiep;

namespace Dft.lms
{
    public class lmsApplicationAutoMapperProfile : Profile
    {
        public lmsApplicationAutoMapperProfile()
        {
            /* You can configure your AutoMapper mapping configuration here.
             * Alternatively, you can split your mapping configurations
             * into multiple profile classes for a better organization. */

            CreateMap<DoanhNghiep, DoanhNghiepDto>();
            CreateMap<CreateUpdateDoanhNghiepDto, DoanhNghiep>();
        }
    }
}
