// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Microsoft.Extensions.DependencyInjection;
using Volo.Abp.Modularity;

namespace Dft.lms.EntityFrameworkCore
{
    [DependsOn(
        typeof(lmsEntityFrameworkCoreModule)
        )]
    public class lmsEntityFrameworkCoreDbMigrationsModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpDbContext<lmsMigrationsDbContext>();
        }
    }
}
