// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Dft.lms.QuanLyDoanhNghiep;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
using Volo.Abp.EntityFrameworkCore.Modeling;

namespace Dft.lms.EntityFrameworkCore
{
    public static class lmsDbContextModelCreatingExtensions
    {
        public static void Configurelms(this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            /* Configure your own tables/entities inside here */

            builder.Entity<DoanhNghiep>(b =>
            {
                b.ToTable(lmsConsts.DbTablePrefix + "DoanhNghiep", lmsConsts.DbSchema);
                b.ConfigureByConvention(); //auto configure for the base class props

                //Properties
                b.Property(q => q.AnhDaiDienDoanhNghiep);
                b.Property(q => q.TenDoanhNghiep).IsRequired().HasMaxLength(lmsDomainSharedConsts.MaxLengthName);
                b.Property(q => q.EmailDoanhNghiep).IsRequired().HasMaxLength(lmsDomainSharedConsts.MaxLengthEmail);
                b.Property(q => q.DiaChiDoanhNghiep).IsRequired().HasMaxLength(lmsDomainSharedConsts.MaxLengthAddress);
                b.Property(q => q.SoDienThoaiDoanhNghiep).IsRequired().HasMaxLength(lmsDomainSharedConsts.MaxLengthPhone);
                b.Property(q => q.NganhNgheDoanhNghiep).HasMaxLength(lmsDomainSharedConsts.MaxLengthName);

                b.Property(q => q.TenNguoiDaiDien).IsRequired().HasMaxLength(lmsDomainSharedConsts.MaxLengthName);
                b.Property(q => q.EmailNguoiDaiDien).IsRequired().HasMaxLength(lmsDomainSharedConsts.MaxLengthEmail);
                b.Property(q => q.ChucVuNguoiDaiDien).HasMaxLength(lmsDomainSharedConsts.MaxLengthName);
                b.Property(q => q.SoDienThoaiNguoiDaiDien).IsRequired().HasMaxLength(lmsDomainSharedConsts.MaxLengthPhone);
            });

            //builder.Entity<YourEntity>(b =>
            //{
            //    b.ToTable(lmsConsts.DbTablePrefix + "YourEntities", lmsConsts.DbSchema);
            //    b.ConfigureByConvention(); //auto configure for the base class props
            //    //...
            //});
        }
    }
}
