// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Dft.lms.Localization;
using Volo.Abp.AspNetCore.Mvc;

namespace Dft.lms.Controllers
{
    /* Inherit your controllers from this class.
     */
    public abstract class lmsController : AbpController
    {
        protected lmsController()
        {
            LocalizationResource = typeof(lmsResource);
        }
    }
}
