// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Dft.lms.EntityFrameworkCore;
using Volo.Abp.Modularity;

namespace Dft.lms
{
    [DependsOn(
        typeof(lmsEntityFrameworkCoreTestModule)
        )]
    public class lmsDomainTestModule : AbpModule
    {

    }
}
