// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
namespace Dft.lms
{
    public abstract class lmsDomainTestBase : lmsTestBase<lmsDomainTestModule> 
    {

    }
}
