// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
namespace Dft.lms
{
    public static class lmsDomainErrorCodes
    {
        /* You can add your business exception error codes here, as constants */
        public const string DoanhNghiepNameAlreadyExists = "LMS:00001";
        public const string DoanhNghiepEmailAlreadyExists = "LMS:00002";
        public const string DoanhNghiepPhoneAlreadyExists = "LMS:00003";
    }
}
