// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Volo.Abp;

namespace Dft.lms.EntityFrameworkCore
{
    public abstract class lmsEntityFrameworkCoreTestBase : lmsTestBase<lmsEntityFrameworkCoreTestModule> 
    {

    }
}
