// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using System.Threading.Tasks;

namespace Dft.lms.Data
{
    public interface IlmsDbSchemaMigrator
    {
        Task MigrateAsync();
    }
}
