// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Volo.Abp.Modularity;

namespace Dft.lms
{
    [DependsOn(
        typeof(lmsApplicationModule),
        typeof(lmsDomainTestModule)
        )]
    public class lmsApplicationTestModule : AbpModule
    {

    }
}
