// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using System.Runtime.CompilerServices;
[assembly:InternalsVisibleToAttribute("Dft.lms.Application.Tests")]
