// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
namespace Dft.lms
{
    public static class lmsConsts
    {
        public const string DbTablePrefix = "App";

        public const string DbSchema = null;
    }
}
