// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Volo.Abp.Localization;

namespace Dft.lms.Localization
{
    [LocalizationResourceName("lms")]
    public class lmsResource
    {

    }
}
