// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Volo.Abp.DependencyInjection;
using Volo.Abp.Ui.Branding;

namespace Dft.lms
{
    [Dependency(ReplaceServices = true)]
    public class lmsBrandingProvider : DefaultBrandingProvider
    {
        public override string AppName => "lms";
    }
}
