// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Volo.Abp.Settings;

namespace Dft.lms.Settings
{
    public class lmsSettingDefinitionProvider : SettingDefinitionProvider
    {
        public override void Define(ISettingDefinitionContext context)
        {
            //Define your own settings here. Example:
            //context.Add(new SettingDefinition(lmsSettings.MySetting1));
        }
    }
}
